services:
  - type: web
    name: records-chest
    env: python
    buildCommand: |
      # Build frontend
      cd ../frontend
      npm install
      npm run build
      # Move build to backend
      cd ..
      mkdir -p backend/frontend
      cp -r frontend/build backend/frontend/
      # Install backend dependencies
      cd backend
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: FRONTEND_URL
        value: https://records-chest.onrender.com