services:
  - type: web
    name: records-chest
    env: python
    buildCommand: |
      # Build frontend
      cd /opt/render/project/src/frontend
      npm install
      npm run build
      # Move build to backend
      mkdir -p /opt/render/project/src/backend/frontend
      cp -r build /opt/render/project/src/backend/frontend/
      # Install backend dependencies
      cd /opt/render/project/src/backend
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: FRONTEND_URL
        value: https://records-chest.onrender.com